
// CUSTOMS HTTP_STATUS_CODE FILE
export const STATUS_CODE = {
    // ✅ SUCCESS RESPONSE
    OK: 200,
    CREATED: 201,
    ACCEPTED: 202,
    NO_CONTENT: 204,

    // ❌ CLIENT ERRORS
    BAD_REQUEST: 400,
    UNAUTHORIZED: 401,
    FORBIDDEN: 403,
    NOT_FOUND: 404,
    CONFLICT: 409,
    UNPROCESSABLE_ENTITY: 422,

    // 💥 SERVER ERRORR 
    INTERNAL_SERVER_ERROR: 500,
    NOT_IMPLEMENTED: 501,
    BAD_GATEWAY: 502,
    SERVICE_UNAVAILABLE: 503,
    GATEWAY_TIMEOUT: 504,
} as const;

export type HttpStatusCode = (typeof STATUS_CODE)[keyof typeof STATUS_CODE];